using System;
using System.Collections.Generic;
using System.IO;
using Snek.Utilities;
using SnekEditor.Utilities;
using UnityEditor;
using UnityEngine;

namespace SnekEditor.ScriptableObjectManager
{
    [InitializeOnLoad]
    public static class SnekScriptableObjectManager
    {
        private const string CacheFilePath = "Assets/Snek/ScriptableObjectManager/SnekScriptableObjectManagerCache.asset";
        private const string MenuItemRoot = SnekEditorUtility.MenuItemRoot + "Scriptable Object Manager/";

        private static SnekScriptableObjectManagerCache _cache;

        private static Action _onInitialized;
        private static bool _isInitialized = false;

        static SnekScriptableObjectManager()
        {
            Initialize();
        }

        [MenuItem(MenuItemRoot + "Show Cache Window")]
        private static void ShowCacheWindow()
        {
            EditorUtility.OpenPropertyEditor(_cache);
        }

        [MenuItem(MenuItemRoot + "Generate Missing Assets")]
        private static void Initialize()
        {
            _cache = AssetDatabase.LoadAssetAtPath<SnekScriptableObjectManagerCache>(CacheFilePath);

            if (!_cache)
                _cache = CreateAsset(typeof(SnekScriptableObjectManagerCache), CacheFilePath) as SnekScriptableObjectManagerCache;

            EditorApplication.delayCall += OnInitializeCache;
        }

        private static void OnInitializeCache()
        {
            EditorApplication.delayCall -= OnInitializeCache;

            InitializeAutoGeneratedAssets();

            _onInitialized?.Invoke();
            _onInitialized = null;

            _isInitialized = true;
        }

        private static void InitializeAutoGeneratedAssets()
        {
            _cache.GeneratedAssets = new List<ScriptableObject>();

            TypeCache.TypeCollection autoGeneratedAssetTypes = TypeCache.GetTypesWithAttribute<SnekAutoGenerateAssetAttribute>();

            foreach (Type type in autoGeneratedAssetTypes)
                InitializeAutoGeneratedAsset(type);
        }

        private static ScriptableObject InitializeAutoGeneratedAsset(Type type)
        {
            if (type.IsAbstract)
            {
                Debug.LogError(
                    $"Type {typeof(Type).Name} is abstract.\n" +
                    $"Cannot generate assets from abstract type.");

                return null;
            }

            if (!SnekEditorUtility.IsAttributeAssignedToType(type, out SnekAutoGenerateAssetAttribute attribute))
                return null;

            ScriptableObject asset = GetAssetFromCache(type);

            if (asset == null)
                asset = AssetDatabase.LoadAssetAtPath(attribute.TargetAssetPath, type) as ScriptableObject;

            if (asset == null)
                asset = CreateAsset(type, attribute.TargetAssetPath);

            _cache.GeneratedAssets.Add(asset);

            EditorUtility.SetDirty(_cache);

            return asset;
        }

        public static T GetAsset<T>() where T : ScriptableObject
        {
            if (!_cache)
                Initialize();

            ScriptableObject asset = GetAssetFromCache(typeof(T));

            if (asset == null)
                asset = InitializeAutoGeneratedAsset(typeof(T));

            return asset as T;
        }

        private static ScriptableObject GetAssetFromCache(Type type)
        {
            return _cache.GeneratedAssets.Find(asset => asset.GetType() == type);
        }

        private static ScriptableObject CreateAsset(Type type, string path)
        {
            var asset = ScriptableObject.CreateInstance(type);

            string directory = Path.GetDirectoryName(path);

            if (!AssetDatabase.IsValidFolder(directory))
            {
                Directory.CreateDirectory(directory);
                AssetDatabase.Refresh();
            }

            AssetDatabase.CreateAsset(asset, path);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log(
                $"Auto-generated missing {type.Name} asset.\n" +
                $"Path: {path}",
                asset);

            return asset;
        }

        /// <summary>
        /// Use this if you want to initialize auto-gen asset references in [InitializeOnLoad] static constructor
        /// from another class to avoid race condition issues
        /// </summary>
        public static void CallAfterInitialization(Action action)
        {
            if (action == null)
                return;

            if (_isInitialized)
                action.Invoke();
            else
                _onInitialized += action;
        }
    }
}
