using System;
using Snek.Utilities;
using SnekEditor.ScriptableObjectManager;
using SnekEditor.Utilities;
using UnityEditor;
using UnityEngine;

namespace SnekEditor.GUIUtilities
{
    [InitializeOnLoad]
    public static class SnekGUIOverrideManager
    {
        private static Texture2D _autoGeneratedAssetIcon;

        static SnekGUIOverrideManager()
        {
            SnekScriptableObjectManager.CallAfterInitialization(ApplyGUIOverrides);
        }

        public static void ApplyGUIOverrides()
        {
            var iconsContainer = SnekScriptableObjectManager.GetAsset<SnekEditorIconsContainer>();

            if (!iconsContainer)
                return;

            _autoGeneratedAssetIcon = iconsContainer.GetLogoThick();

            EditorApplication.projectWindowItemOnGUI -= DrawProjectWindowGUI;
            EditorApplication.projectWindowItemOnGUI += DrawProjectWindowGUI;
        }

        private static void DrawProjectWindowGUI(string guid, Rect rect)
        {
            if (_autoGeneratedAssetIcon == null)
                return;

            Type type = AssetDatabase.GetMainAssetTypeFromGUID(new GUID(guid));

            if (type != typeof(SnekScriptableObjectManagerCache))
            {
                if (type == null || !type.IsSubclassOf(typeof(SnekScriptableObject)))
                    return;

                if (!SnekEditorUtility.IsAttributeAssignedToType<SnekAutoGenerateAssetAttribute>(type, out _))
                    return;
            }

            OverrideAutoGeneratedAssetIcons(rect);
        }

        private static void OverrideAutoGeneratedAssetIcons(Rect rect)
        {
            bool isLargeIconMode = rect.width < rect.height;
            bool isTwoColumnLayout = rect.x < 30f;

            bool isTwoColumnSmallIconMode = !isLargeIconMode && isTwoColumnLayout;

            var iconRect = new Rect()
            {
                x = isTwoColumnSmallIconMode ? rect.x + 3f : rect.x,
                y = rect.y,
                width = isLargeIconMode ? rect.width : rect.height,
                height = isLargeIconMode ? rect.width : rect.height,
            };

            var backgroundRect = new Rect(iconRect)
            {
                width = iconRect.width + 3f,
            };

            var darkThemeColor = new Color(0.219f, 0.219f, 0.219f);
            var lightThemeColor = new Color(0.760f, 0.760f, 0.760f);

            Color backgroundColor = EditorGUIUtility.isProSkin ?
                darkThemeColor : lightThemeColor;

            EditorGUI.DrawRect(backgroundRect, backgroundColor);
            GUI.DrawTexture(iconRect, _autoGeneratedAssetIcon);
        }
    }
}
